package com.ms.magasinbe.common.utils;

public interface ConstantData {

  // otp
  String OTP_IS_INCORRECT = "OTP_IS_INCORRECT";
  String OTP_CANNOT_BE_USED_ANYMORE = "OTP_CANNOT_BE_USED_ANYMORE";
  String EMAIL_HAS_BEEN_RECEIVED_OTP_NOTFOUND = "EMAIL_HAS_BEEN_RECEIVED_OTP_NOTFOUND";
  String OTP_HAS_EXPIRED = "OTP_HAS_EXPIRED";
  String USER_NOT_FOUND = "USER_NOT_FOUND";
  String WRONG_PASSWORD = "WRONG_PASSWORD";
  String PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH";
  String PHONE_NUMBER_ALREADY_EXISTED = "PHONE_NUMBER_ALREADY_EXISTED";
  String EMAIL_ALREADY_EXISTED = "EMAIL_ALREADY_EXISTED";
  String INVALID_PAGING_REQUEST = "INVALID_PAGING_REQUEST";
  String INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT";
  String CANNOT_FORGOT_PASSWORD = "CANNOT_FORGOT_PASSWORD";
}
